### ISSUE TITLE
More compact

### ISSUE THREAD

**Issue by dsyme** [adelarsq/fsharp-cheatsheet#2]
Just a note that realistically we can make this much more compact I think, either here or on the .NET docs version

For example all the collection functions can just be in a table, with links to https://github.com/fsharp/fsharp-core-docs since each of the functions now have examples on the documentation pages.

**Comment by adelarsq** [comment]
While ago I did some work on this.
I am planning for some more changes on the revision for F# 8 on next days or weeks (on my free time).
